spring.application.name=task-manager-service
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.open-in-view=false

## H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:taskdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#
## SQL Initialization
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true


spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=myuser
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (if using Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional (debugging)
spring.jpa.show-sql=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.task=DEBUG

# Swagger / OpenAPI Documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Server Port
server.port=8085

# Spring Boot Actuator Endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.info.env.enabled=true

# Application Info
info.app.name=${spring.application.name}
info.app.description=Task management REST API
info.app.version=@project.version@